version: '3'
services:
  proxy:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    networks:
      - frontend
    depends_on:
      - php
      - php2
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
  serveur1:
    build: './serveur1/'
    networks:
      - frontend
      - backend1
    depends_on:
      - php
      - mariadb
    volumes:
      - './serveur1/html:/srv/htdocs'
  serveur2:
    build: './serveur2/'
    networks:
      - frontend
      - backend2
    depends_on:
      - php2
      - mariadb
    volumes:
      - './serveur2/html:/srv/htdocs'
  php:
    networks:
      - backend1
    volumes:
      - './serveur1/html:/srv/htdocs'
    build: './php/'
  php2:
    networks:
      - backend2
    volumes:
      - './serveur2/html:/srv/htdocs'
    build: './php2/'
  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend1
      - backend2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
        #    ports:
        #- '3306:3306'
networks:
  frontend:
  backend1:
  backend2:
volumes:
  dbdata:
